# IRIS

In [1]:
import os
os.chdir(r'C:\Users\Lenovo\Desktop\machine learning')

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv('iris.data')

In [4]:
dataset

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [5]:
x=dataset.iloc[:,1:4].values

In [6]:
y=dataset.iloc[:,4]

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


In [8]:
print("error showing")

error showing


'' RUNNING 1ST MODEL USING LOGISTIC REGRESSION MODEL CONCEPT '' 

In [9]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [10]:
y_pred=logmodel.predict(x_test)

In [11]:
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [12]:
y_test

99      Iris-virginica
9          Iris-setosa
65     Iris-versicolor
109     Iris-virginica
60     Iris-versicolor
143     Iris-virginica
63     Iris-versicolor
114     Iris-virginica
38         Iris-setosa
14         Iris-setosa
4          Iris-setosa
19         Iris-setosa
43         Iris-setosa
121     Iris-virginica
147     Iris-virginica
16         Iris-setosa
7          Iris-setosa
68     Iris-versicolor
72     Iris-versicolor
58     Iris-versicolor
102     Iris-virginica
15         Iris-setosa
35         Iris-setosa
80     Iris-versicolor
96     Iris-versicolor
95     Iris-versicolor
126     Iris-virginica
119     Iris-virginica
105     Iris-virginica
73     Iris-versicolor
Name: Iris-setosa, dtype: object

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [14]:
26/30

0.8666666666666667

KNN NEIGHBORS ALGORITHM

In [15]:
from sklearn.neighbors import KNeighborsClassifier
Classifier_Knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
Classifier_Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
y_pred=Classifier_Knn.predict(x_test)

In [17]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [18]:
28/30

0.9333333333333333

In [19]:
print("93% accuracy")

93% accuracy


In [20]:
0.93*100

93.0

In [21]:
from sklearn.naive_bayes import GaussianNB
Classifier_nb=GaussianNB()
Classifier_nb.fit(x_train,y_train)

GaussianNB()

In [22]:
y_pred=Classifier_nb.predict(x_test)

In [23]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [24]:
27/30

0.9

In [25]:
0.9*100

90.0

In [26]:
print("90% accurate")

90% accurate


In [27]:
from sklearn.svm import SVC
classifier_svm_sigmoid=SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [28]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [29]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0, 10],
       [ 0,  0, 10],
       [ 9,  0,  1]], dtype=int64)

In [30]:
print("modle accuracy is lowset in this case")

modle accuracy is lowset in this case


In [31]:
7/30

0.23333333333333334

In [32]:
0.233*100

23.3

In [33]:
print("23.3 % is accuracy")

23.3 % is accuracy


In [34]:
from sklearn.svm import SVC
classifier_svm_linear=SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [35]:
y_pred=classifier_svm_linear.predict(x_test)

In [36]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [37]:
print("accuracy is very good")

accuracy is very good


In [38]:
12+5+11

28

In [39]:
28/30

0.9333333333333333

In [40]:
0.933*100

93.30000000000001

In [41]:
print("93% accuracy")

93% accuracy


In [42]:
from sklearn.svm import SVC
classifier_svm_rbf=SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [43]:
y_pred=classifier_svm_rbf.predict(x_test)

In [44]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [45]:
27/30

0.9

In [46]:
0.9*100

90.0

In [47]:
print("it gives 90% accuracy")

it gives 90% accuracy


In [48]:
from sklearn.svm import SVC
classifier_svm_poly=SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [49]:
y_pred=classifier_svm_poly.predict(x_test)

In [50]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  9]], dtype=int64)

In [51]:
28/30

0.9333333333333333

In [52]:
0.933*100

93.30000000000001

In [53]:
print("it also gives 93% accuracy")

it also gives 93% accuracy


In [54]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt=DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [55]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt=DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [59]:
y_pred=classifier_dt.predict(x_test)

In [60]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]], dtype=int64)

In [61]:
print("it gives best accuracy a complete 100%")

it gives best accuracy a complete 100%


In [63]:
30/30

1.0

In [64]:
1.0*100

100.0

In [65]:
print("100%")

100%


In [67]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3,criterion='entropy')
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [68]:
y_pred=classifier_rf.predict(x_test)

In [69]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  1,  9]], dtype=int64)

In [70]:
print("it also give preety much good accuracy")

it also give preety much good accuracy


In [71]:
12+8+9

29

In [72]:
29/30

0.9666666666666667

In [73]:
0.966*100

96.6

In [74]:
print("it gives 96% accuracy")

it gives 96% accuracy


WE APPLY DIFFERENT DIFFERNENT MODELS LIKE LOGISTIC REGRESSION, K NEAREST NEIGHBOR (KNN),SUPPORT VECTOR MACHINE(SVM),decision tree , ensemble 
ALSO WE APPLY ALL SVM PARTS LIKE POLY,LINEAR,rbf,sigmoid TO GET BEST ACCURACY FOR OUR MODEL USING SKLEARN.
                                 WE CAN SAY THIS IS SKLEAREN

# CONCLUDED